export const likesDislikes = [
  'hugs',
  'pets',
  'walks',
  'sniffs',
  'horses',
  'outdoors',
  'cars',
  'bicycles',
  'roads',
  'grass',
  'ball games',
  'children',
  'other pets',
  'hot',
  'cold',
  'fireworks',
];

export const matches = [
  {
    userId: '4jg6OCap5PQ3FANMuoG1FONJBvF2',
    matched: ['HsUxOdRgSbeq2oxCgAIox63m8oA3', 'pBpXPtTC8tP3ARlhUn45IzHgKyp2'],
  },
  {
    userId: 'HsUxOdRgSbeq2oxCgAIox63m8oA3',
    matched: ['8qw4gtm1VhWfcQDlfdNw7y9sQVm2'],
  },
  {
    userId: '8qw4gtm1VhWfcQDlfdNw7y9sQVm2',
    matched: ['HsUxOdRgSbeq2oxCgAIox63m8oA3', 'Z9R01fG87SYOQg1ASouLqPDskso2'],
  },
  {
    userId: 'pBpXPtTC8tP3ARlhUn45IzHgKyp2',
    matched: ['4jg6OCap5PQ3FANMuoG1FONJBvF2', 'Z9R01fG87SYOQg1ASouLqPDskso2'],
  },
  {
    userId: 'Z9R01fG87SYOQg1ASouLqPDskso2',
    matched: ['8qw4gtm1VhWfcQDlfdNw7y9sQVm2', 'pBpXPtTC8tP3ARlhUn45IzHgKyp2'],
  },
];

export const users = [
  {
    userId: '4jg6OCap5PQ3FANMuoG1FONJBvF2',
    name: 'Keval',
    email: 'keval@test.com',
    location: {
      city: 'London',
      county: 'Greater London',
      state: 'England',
      postcode: 'SE1 4YR',
      country: 'United Kingdom',
      countryCode: 'gb',
      lon: -0.09292904665889001,
      lat: 51.49983975,
      stateCode: 'ENG',
      formatted:
        'CAN Mezzanine, 7-14 Great Dover Street, London, SE1 4YR, United Kingdom',
      addressLine1: 'CAN Mezzanine',
      addressLine2: '7-14 Great Dover Street, London, SE1 4YR, United Kingdom',
    },
    verified: true,
    notifications: true,
    darkMode: false,
    swipeYes: [],
    swipeNo: [],
    matches: [],
    ownerImage:
      'https://png.pngtree.com/png-vector/20191027/ourlarge/pngtree-user-icon-isolated-on-abstract-background-png-image_1875037.jpg',
    dog: {
      name: 'Hendrix',
      breed: 'Maltese',
      age: 5,
      size: 'Small',
      gender: 'Male',
      energyLevel: 3,
      dogFriendliness: 3,
      humanFriendliness: 4,
      images: [
        'https://images.dog.ceo/breeds/maltese/n02085936_4506.jpg',
        'https://images.dog.ceo/breeds/maltese/n02085936_899.jpg',
        'https://images.dog.ceo/breeds/maltese/n02085936_5488.jpg',
      ],
      description:
        "I'm born and raised in Watford, enjoying my daily walks alongside River Colne. I mostly enjoy barking with other dogs and not at them",
      briefDescription:
        "I'm a happy maltese looking for a companion to walk and bark with.",
      likes: ['sniffs', 'horses', 'outdoors'],
      dislikes: ['cars', 'bicycles', 'fireworks'],
    },
    preferences: {
      size: ['Small', 'Medium'],
      maxDistance: 4,
      gender: 'Male',
      energyLevel: [2, 3, 4],
    },
  },
  {
    userId: 'HsUxOdRgSbeq2oxCgAIox63m8oA3',
    name: 'Kevin',
    email: 'kevin@test.com',
    location: {
      city: 'London',
      county: 'Greater London',
      state: 'England',
      postcode: 'SE1 0AR',
      country: 'United Kingdom',
      countryCode: 'gb',
      lon: -0.08947282617611846,
      lat: 51.50335215,
      stateCode: 'ENG',
      formatted:
        'Roman Southwark, 18–20 Newcomen Street, London, SE1 0AR, United Kingdom',
      addressLine1: 'Roman Southwark',
      addressLine2: '18–20 Newcomen Street, London, SE1 0AR, United Kingdom',
    },
    verified: true,
    notifications: true,
    darkMode: true,
    swipeYes: [],
    swipeNo: [],
    matches: [],
    ownerImage:
      'https://png.pngtree.com/png-vector/20191027/ourlarge/pngtree-user-icon-isolated-on-abstract-background-png-image_1875037.jpg',
    dog: {
      name: 'Bear',
      breed: 'Husky',
      age: 6,
      size: 'Medium',
      gender: 'Male',
      energyLevel: 4,
      dogFriendliness: 3,
      humanFriendliness: 3,
      images: [
        'https://images.dog.ceo/breeds/husky/n02110185_4186.jpg',
        'https://images.dog.ceo/breeds/husky/n02110185_1614.jpg',
        'https://images.dog.ceo/breeds/husky/n02110185_10047.jpg',
      ],
      description:
        'Been a sled dog from my early teenage years, roaming northern Norway. Currently I enjoy to trek the forests of nothern London, going for a occasional swim.',
      briefDescription: 'A howling husky looking for company',
      likes: ['sniffs', 'horses', 'outdoors', 'hugs', 'pets'],
      dislikes: ['hot', 'cars', 'bicycles', 'fireworks'],
    },
    preferences: {
      size: ['Medium', 'Small'],
      maxDistance: 5,
      gender: 'Male',
      energyLevel: [2, 3, 4],
    },
  },
  {
    userId: '8qw4gtm1VhWfcQDlfdNw7y9sQVm2',
    name: 'Freya',
    email: 'freya@test.com',
    location: {
      city: 'London',
      county: 'Greater London',
      state: 'England',
      postcode: 'SE1 1DF',
      country: 'United Kingdom',
      countryCode: 'gb',
      lon: -0.0946555,
      lat: 51.4989975,
      stateCode: 'ENG',
      formatted:
        'Gloucester Court, Swan Street, London, SE1 1DF, United Kingdom',
      addressLine1: 'Gloucester Court',
      addressLine2: 'Swan Street, London, SE1 1DF, United Kingdom',
    },
    verified: true,
    notifications: true,
    darkMode: true,
    swipeYes: [],
    swipeNo: [],
    matches: [],
    ownerImage:
      'https://png.pngtree.com/png-vector/20191027/ourlarge/pngtree-user-icon-isolated-on-abstract-background-png-image_1875037.jpg',
    dog: {
      name: 'Lacey',
      breed: 'Golden Retriever',
      age: 5,
      size: 'Medium',
      gender: 'Female',
      energyLevel: 3,
      dogFriendliness: 4,
      humanFriendliness: 4,
      images: [
        'https://images.dog.ceo/breeds/retriever-golden/n02099601_6820.jpg',
        'https://images.dog.ceo/breeds/retriever-golden/n02099601_2691.jpg',
        'https://images.dog.ceo/breeds/retriever-golden/nina.jpg',
      ],
      description:
        'My owner have had me at her surfboard since 3 months of age, hence I love water. I go mountainbiking with her on the weekends and would love to have a companion join the fun.',
      briefDescription:
        'Calm friendly dog who enjoys to go surfing and biking.',
      likes: ['sniffs', 'horses', 'outdoors', 'hugs', 'pets'],
      dislikes: ['hot', 'cars', 'bicycles', 'fireworks'],
    },
    preferences: {
      size: ['Small', 'Medium', 'Large'],
      maxDistance: 3,
      gender: 'Female',
      energyLevel: [2, 3, 4],
    },
  },
  {
    userId: 'pBpXPtTC8tP3ARlhUn45IzHgKyp2',
    name: 'Andreas',
    email: 'andreas@test.com',
    location: {
      city: 'London',
      county: 'Greater London',
      state: 'England',
      postcode: 'SE1 8QH',
      country: 'United Kingdom',
      countryCode: 'gb',
      lon: -0.10572646114155257,
      lat: 51.5016975,
      stateCode: 'ENG',
      result_type: 'building',
      formatted: '5 Valentine Place, London, SE1 8QH, United Kingdom',
      addressLine1: '5 Valentine Place',
      addressLine2: 'London, SE1 8QH, United Kingdom',
    },
    verified: true,
    notifications: true,
    darkMode: false,
    swipeYes: [],
    swipeNo: [],
    matches: [],
    ownerImage:
      'https://png.pngtree.com/png-vector/20191027/ourlarge/pngtree-user-icon-isolated-on-abstract-background-png-image_1875037.jpg',
    dog: {
      name: 'Cleo',
      breed: '',
      age: 4,
      size: 'Medium',
      gender: 'Female',
      energyLevel: 3,
      dogFriendliness: 4,
      humanFriendliness: 3,
      images: [
        'https://images.dog.ceo/breeds/samoyed/n02111889_10059.jpg',
        'https://images.dog.ceo/breeds/samoyed/n02111889_2136.jpg',
        'https://images.dog.ceo/breeds/samoyed/n02111889_2650.jpg',
      ],
      description:
        "If you are looking for a friend to tumble with, look no further. Walks, wrestles, even agility training. I have the full package. I'm too fluffy to let go!",
      briefDescription:
        'Fluffy friendly canine looking for a wrestling partner.',
      likes: ['sniffs', 'horses', 'outdoors', 'hugs', 'pets'],
      dislikes: ['hot', 'cars', 'bicycles', 'fireworks'],
    },
    preferences: {
      size: ['Small', 'Medium'],
      maxDistance: 0.75,
      gender: 'Female',
      energyLevel: [2, 3, 4],
    },
  },
  {
    userId: 'Z9R01fG87SYOQg1ASouLqPDskso2',
    name: 'Kara',
    email: 'kara@test.com',
    location: {
      countryCode: 'gb',
      country: 'United Kingdom',
      city: 'London',
      state: 'England',
      postcode: 'SE17',
      county: 'Greater London',
      lon: -0.092989,
      lat: 51.491489,
      stateCode: 'ENG',
      formatted: '22-44 Walters Close, London, SE17, United Kingdom',
      addressLine1: '22-44 Walters Close',
      addressLine2: 'London, SE17, United Kingdom',
    },
    verified: true,
    notifications: true,
    darkMode: false,
    swipeYes: [],
    swipeNo: [],
    matches: [],
    ownerImage:
      'https://png.pngtree.com/png-vector/20191027/ourlarge/pngtree-user-icon-isolated-on-abstract-background-png-image_1875037.jpg',
    dog: {
      name: 'Hannah',
      breed: '',
      age: 3,
      size: 'Medium',
      gender: 'Female',
      energyLevel: 4,
      dogFriendliness: 4,
      humanFriendliness: 3,
      images: [
        'https://images.dog.ceo/breeds/germanshepherd/n02106662_13912.jpg',
        'https://images.dog.ceo/breeds/germanshepherd/n02106662_16149.jpg',
        'https://images.dog.ceo/breeds/germanshepherd/Hannah.jpg',
      ],
      description:
        "I especially like going to the forest. I'm trained in finding eatable mushrooms, so your owner might want to skip dinner reservations.",
      briefDescription: 'Forest loving dog up for anything outdoors.',
      likes: ['sniffs', 'horses', 'outdoors', 'hugs', 'pets'],
      dislikes: ['hot', 'cars', 'bicycles', 'fireworks'],
    },
    preferences: {
      size: ['Small', 'Medium', 'Large'],
      maxDistance: 0.5,
      gender: 'Both',
      energyLevel: [2, 3, 4],
    },
  },
  {
    userId: 'VctUVBo8YbX8hGYSVNM5vrLVtg13',
    name: 'Alex',
    email: 'alex@test.com',
    location: {
      countryCode: 'gb',
      country: 'United Kingdom',
      city: 'London',
      state: 'England',
      postcode: 'SE1 4HU"',
      county: 'Greater London',
      lon: -0.094505,
      lat: 51.498161,
      stateCode: 'ENG',
      formatted:
        'Rutherford Lodge, 7 Brockham Street, London, SE1 4HU, United Kingdom',
      addressLine1: 'Rutherford Lodge',
      addressLine2: '7 Brockham Street, London, SE1 4HU, United Kingdom',
    },
    verified: false,
    notifications: true,
    darkMode: false,
    swipeYes: [],
    swipeNo: [],
    matches: [],
    ownerImage:
      'https://png.pngtree.com/png-vector/20191027/ourlarge/pngtree-user-icon-isolated-on-abstract-background-png-image_1875037.jpg',
    dog: {
      name: 'Emma',
      breed: 'Mix',
      age: 2,
      size: 'Medium',
      gender: 'Female',
      energyLevel: 3,
      dogFriendliness: 3,
      humanFriendliness: 4,
      description:
        'If you enjoy catching frisbees in the park, we are meant for eachother!',
      briefDescription: 'Frisbee lover!',
      likes: ['frisbee', 'horses', 'outdoors'],
      dislikes: ['cars', 'bicycles', 'fireworks'],
    },
    preferences: {
      size: ['Small', 'Medium'],
      maxDistance: 4,
      gender: 'Male',
      energyLevel: [2, 3, 4],
    },
  },
  {
    userId: 'jUIXoPI1tOMbFOXwph9YStubqZT2',
    name: 'James',
    email: 'james@test.com',
    location: {
      countryCode: 'gb',
      country: 'United Kingdom',
      city: 'London',
      state: 'England',
      postcode: 'SE17',
      county: 'Greater London',
      lon: -0.0922512,
      lat: 51.4977061,
      stateCode: 'ENG',
      formatted: 'Merrick Square, London, SE1 4JB, United Kingdom',
      addressLine1: 'Merrick Square',
      addressLine2: 'London, SE1 4JB, United Kingdom',
    },
    verified: true,
    notifications: true,
    darkMode: false,
    swipeYes: [],
    swipeNo: [],
    matches: [],
    ownerImage:
      'https://png.pngtree.com/png-vector/20191027/ourlarge/pngtree-user-icon-isolated-on-abstract-background-png-image_1875037.jpg',
    dog: {
      name: 'Berty',
      breed: 'Beagle',
      age: 3,
      size: 'Medium',
      gender: 'Male',
      energyLevel: 4,
      dogFriendliness: 4,
      humanFriendliness: 3,
      images: [
        'https://images.dog.ceo/breeds/beagle/n02088364_639.jpg',
        'https://images.dog.ceo/breeds/beagle/n02088364_14613.jpg',
        'https://images.dog.ceo/breeds/beagle/n02088364_14690.jpg',
      ],
      description:
        "I grew up with a lot of dogs and since I got adopted I've missed being in a pack. I'll make friends with just about any dog.",
      briefDescription: 'Seeking a group of like minded dogs.',
      likes: ['sniffs', 'horses', 'outdoors', 'hugs', 'pets'],
      dislikes: ['hot', 'cars', 'bicycles', 'fireworks'],
    },
    preferences: {
      size: ['Small', 'Medium', 'Large'],
      maxDistance: 0.75,
      gender: 'Both',
      energyLevel: [2, 3, 4],
    },
  },
  {
    userId: 'VzQh0Rz6oOcceVK9pqPSovIZRLm1',
    name: 'Raul',
    email: 'raul@test.com',
    location: {
      countryCode: 'gb',
      country: 'United Kingdom',
      city: 'London',
      state: 'England',
      postcode: 'SE1 4YG',
      county: 'Greater London',
      lon: -0.09139095000000394,
      lat: 51.49866165,
      stateCode: 'ENG',
      formatted: 'Shere House, Trinity Street, London, SE1 4YG, United Kingdom',
      addressLine1: 'Shere House',
      addressLine2: 'Trinity Street, London, SE1 4YG, United Kingdom',
    },
    verified: false,
    notifications: true,
    darkMode: false,
    swipeYes: [],
    swipeNo: [],
    matches: [],
    ownerImage:
      'https://png.pngtree.com/png-vector/20191027/ourlarge/pngtree-user-icon-isolated-on-abstract-background-png-image_1875037.jpg',
    dog: {
      name: 'Maya',
      breed: 'Pyreness',
      age: 6,
      size: 'Medium',
      gender: 'Female',
      energyLevel: 4,
      dogFriendliness: 4,
      humanFriendliness: 3,
      images: [
        'https://images.dog.ceo/breeds/pyrenees/n02111500_8319.jpg',
        'https://images.dog.ceo/breeds/pyrenees/n02111500_2617.jpg',
        'https://images.dog.ceo/breeds/pyrenees/n02111500_7218.jpg',
      ],
      description:
        'My name is Maya. I bark spanish but also english. Hit me up if you want to train your language skills!',
      briefDescription: 'Habla espanõl? I am seeking an amigo/amiga.',
      likes: ['sniffs', 'horses', 'outdoors', 'hugs', 'pets'],
      dislikes: ['hot', 'cars', 'bicycles', 'fireworks'],
    },
    preferences: {
      size: ['Small', 'Medium', 'Large'],
      maxDistance: 0.75,
      gender: 'Both',
      energyLevel: [2, 3, 4],
    },
  },
];
