export const users = [
  {
    userId: '4jg6OCap5PQ3FANMuoG1FONJBvF2',
    name: 'Keval',
    email: 'keval@test.com',
    location: {
      city: 'London',
      county: 'Greater London',
      state: 'England',
      postcode: 'SE1 4YR',
      country: 'United Kingdom',
      countryCode: 'gb',
      lon: -0.09292904665889001,
      lat: 51.49983975,
      stateCode: 'ENG',
      formatted:
        'CAN Mezzanine, 7-14 Great Dover Street, London, SE1 4YR, United Kingdom',
      addressLine1: 'CAN Mezzanine',
      addressLine2: '7-14 Great Dover Street, London, SE1 4YR, United Kingdom',
    },
    verified: true,
    notifications: true,
    darkMode: false,
    swipeYes: [
      'VzQh0Rz6oOcceVK9pqPSovIZRLm1',
      'jUIXoPI1tOMbFOXwph9YStubqZT2',
      'Z9R01fG87SYOQg1ASouLqPDskso2',
      'pBpXPtTC8tP3ARlhUn45IzHgKyp2',
      'HsUxOdRgSbeq2oxCgAIox63m8oA3',
      'VctUVBo8YbX8hGYSVNM5vrLVtg13',
      '8qw4gtm1VhWfcQDlfdNw7y9sQVm2',
    ],
    swipeNo: [],
    matches: [
      {
        matchId: 'VzQh0Rz6oOcceVK9pqPSovIZRLm1',
        roomId: 'VzQh0Rz6oO4jg6OCap5P',
      },
      {
        matchId: 'Z9R01fG87SYOQg1ASouLqPDskso2',
        roomId: 'Z9R01fG87S4jg6OCap5P',
      },
    ],
    ownerImage:
      'https://png.pngtree.com/png-vector/20191027/ourlarge/pngtree-user-icon-isolated-on-abstract-background-png-image_1875037.jpg',
    dog: {
      name: 'Hendrix',
      breed: 'Maltese',
      age: 5,
      size: 'Small',
      gender: 'Male',
      energyLevel: 3,
      dogFriendliness: 3,
      humanFriendliness: 4,
      description:
        "I'm born and raised in Watford, enjoying my daily walks alongside River Colne. I mostly enjoy barking with other dogs and not at them",
      briefDescription:
        "I'm a happy maltese looking for a companion to walk and bark with.",
      likes: ['sniffs', 'horses', 'outdoors'],
      dislikes: ['cars', 'bicycles', 'fireworks'],
      images: [
        'https://images.dog.ceo/breeds/maltese/n02085936_4506.jpg',
        'https://images.dog.ceo/breeds/maltese/n02085936_899.jpg',
        'https://images.dog.ceo/breeds/maltese/n02085936_5488.jpg',
      ],
    },
    preferences: {
      size: ['Small', 'Medium'],
      maxDistance: 4,
      gender: 'Male',
      energyLevel: [2, 3, 4],
    },
  },
  {
    userId: 'HsUxOdRgSbeq2oxCgAIox63m8oA3',
    name: 'Kevin',
    email: 'kevin@test.com',
    location: {
      city: 'London',
      county: 'Greater London',
      state: 'England',
      postcode: 'SE1 0AR',
      country: 'United Kingdom',
      countryCode: 'gb',
      lon: -0.08947282617611846,
      lat: 51.50335215,
      stateCode: 'ENG',
      formatted:
        'Roman Southwark, 18–20 Newcomen Street, London, SE1 0AR, United Kingdom',
      addressLine1: 'Roman Southwark',
      addressLine2: '18–20 Newcomen Street, London, SE1 0AR, United Kingdom',
    },
    verified: true,
    notifications: true,
    darkMode: true,
    swipeYes: [],
    swipeNo: [],
    matches: [],
    ownerImage:
      'https://png.pngtree.com/png-vector/20191027/ourlarge/pngtree-user-icon-isolated-on-abstract-background-png-image_1875037.jpg',
    dog: {
      name: 'Bear',
      breed: 'Husky',
      age: 6,
      size: 'Medium',
      gender: 'Male',
      energyLevel: 4,
      dogFriendliness: 3,
      humanFriendliness: 3,
      description:
        'Been a sled dog from my early teenage years, roaming northern Norway. Currently I enjoy to trek the forests of nothern London, going for a occasional swim.',
      briefDescription: 'A howling husky looking for company',
      likes: ['sniffs', 'horses', 'outdoors', 'hugs', 'pets'],
      dislikes: ['hot', 'cars', 'bicycles', 'fireworks'],
      images: [
        'https://images.dog.ceo/breeds/husky/n02110185_4186.jpg',
        'https://images.dog.ceo/breeds/husky/n02110185_1614.jpg',
        'https://images.dog.ceo/breeds/husky/n02110185_10047.jpg',
      ],
    },
    preferences: {
      size: ['Medium', 'Small'],
      maxDistance: 5,
      gender: 'Male',
      energyLevel: [2, 3, 4],
    },
  },
  {
    userId: '8qw4gtm1VhWfcQDlfdNw7y9sQVm2',
    name: 'Freya',
    email: 'freya@test.com',
    location: {
      city: 'London',
      county: 'Greater London',
      state: 'England',
      postcode: 'SE1 1DF',
      country: 'United Kingdom',
      countryCode: 'gb',
      lon: -0.0946555,
      lat: 51.4989975,
      stateCode: 'ENG',
      formatted:
        'Gloucester Court, Swan Street, London, SE1 1DF, United Kingdom',
      addressLine1: 'Gloucester Court',
      addressLine2: 'Swan Street, London, SE1 1DF, United Kingdom',
    },
    verified: true,
    notifications: true,
    darkMode: true,
    swipeYes: ['VzQh0Rz6oOcceVK9pqPSovIZRLm1', 'Z9R01fG87SYOQg1ASouLqPDskso2'],
    swipeNo: [],
    matches: [
      {
        matchId: 'Z9R01fG87SYOQg1ASouLqPDskso2',
        roomId: '8qw4gtm1VhZ9R01fG87S',
      },
      {
        matchId: 'VzQh0Rz6oOcceVK9pqPSovIZRLm1',
        roomId: '8qw4gtm1VhVzQh0Rz6oO',
      },
    ],
    ownerImage:
      'https://png.pngtree.com/png-vector/20191027/ourlarge/pngtree-user-icon-isolated-on-abstract-background-png-image_1875037.jpg',
    dog: {
      name: 'Lacey',
      breed: 'Golden Retriever',
      age: 5,
      size: 'Medium',
      gender: 'Female',
      energyLevel: 3,
      dogFriendliness: 4,
      humanFriendliness: 4,
      description:
        'My owner have had me at her surfboard since 3 months of age, hence I love water. I go mountainbiking with her on the weekends and would love to have a companion join the fun.',
      briefDescription:
        'Calm friendly dog who enjoys to go surfing and biking.',
      likes: ['sniffs', 'horses', 'outdoors', 'hugs', 'pets'],
      dislikes: ['hot', 'cars', 'bicycles', 'fireworks'],
      images: [
        'https://images.dog.ceo/breeds/retriever-golden/n02099601_6820.jpg',
        'https://images.dog.ceo/breeds/retriever-golden/n02099601_2691.jpg',
        'https://images.dog.ceo/breeds/retriever-golden/nina.jpg',
      ],
    },
    preferences: {
      size: ['Small', 'Medium', 'Large'],
      maxDistance: 5,
      gender: 'Female',
      energyLevel: [2, 3, 4],
    },
  },
  {
    userId: 'pBpXPtTC8tP3ARlhUn45IzHgKyp2',
    name: 'Andreas',
    email: 'andreas@test.com',
    location: {
      city: 'London',
      county: 'Greater London',
      state: 'England',
      postcode: 'SE1 8QH',
      country: 'United Kingdom',
      countryCode: 'gb',
      lon: -0.10572646114155257,
      lat: 51.5016975,
      stateCode: 'ENG',
      formatted: '5 Valentine Place, London, SE1 8QH, United Kingdom',
      addressLine1: '5 Valentine Place',
      addressLine2: 'London, SE1 8QH, United Kingdom',
    },
    verified: true,
    notifications: true,
    darkMode: false,
    swipeYes: [],
    swipeNo: [],
    matches: [],
    ownerImage:
      'https://png.pngtree.com/png-vector/20191027/ourlarge/pngtree-user-icon-isolated-on-abstract-background-png-image_1875037.jpg',
    dog: {
      name: 'Cleo',
      breed: '',
      age: 4,
      size: 'Medium',
      gender: 'Female',
      energyLevel: 3,
      dogFriendliness: 4,
      humanFriendliness: 3,
      description:
        "If you are looking for a friend to tumble with, look no further. Walks, wrestles, even agility training. I have the full package. I'm too fluffy to let go!",
      briefDescription:
        'Fluffy friendly canine looking for a wrestling partner.',
      likes: ['sniffs', 'horses', 'outdoors', 'hugs', 'pets'],
      dislikes: ['hot', 'cars', 'bicycles', 'fireworks'],
      images: [
        'https://images.dog.ceo/breeds/samoyed/n02111889_10059.jpg',
        'https://images.dog.ceo/breeds/samoyed/n02111889_2136.jpg',
        'https://images.dog.ceo/breeds/samoyed/n02111889_2650.jpg',
      ],
    },
    preferences: {
      size: ['Small', 'Medium'],
      maxDistance: 0.75,
      gender: 'Female',
      energyLevel: [2, 3, 4],
    },
  },
  {
    userId: 'Z9R01fG87SYOQg1ASouLqPDskso2',
    name: 'Kara',
    email: 'kara@test.com',
    location: {
      city: 'London',
      county: 'Greater London',
      state: 'England',
      postcode: 'SE17',
      country: 'United Kingdom',
      countryCode: 'gb',
      lon: -0.092989,
      lat: 51.491489,
      stateCode: 'ENG',
      formatted: '22-44 Walters Close, London, SE17, United Kingdom',
      addressLine1: '22-44 Walters Close',
      addressLine2: 'London, SE17, United Kingdom',
    },
    verified: true,
    notifications: true,
    darkMode: false,
    swipeYes: [
      'pBpXPtTC8tP3ARlhUn45IzHgKyp2',
      '4jg6OCap5PQ3FANMuoG1FONJBvF2',
      'VctUVBo8YbX8hGYSVNM5vrLVtg13',
      '8qw4gtm1VhWfcQDlfdNw7y9sQVm2',
    ],
    swipeNo: [],
    matches: [
      {
        matchId: '8qw4gtm1VhWfcQDlfdNw7y9sQVm2',
        roomId: '8qw4gtm1VhZ9R01fG87S',
      },
      {
        matchId: '4jg6OCap5PQ3FANMuoG1FONJBvF2',
        roomId: 'Z9R01fG87S4jg6OCap5P',
      },
    ],
    ownerImage:
      'https://png.pngtree.com/png-vector/20191027/ourlarge/pngtree-user-icon-isolated-on-abstract-background-png-image_1875037.jpg',
    dog: {
      name: 'Hannah',
      breed: '',
      age: 3,
      size: 'Medium',
      gender: 'Female',
      energyLevel: 4,
      dogFriendliness: 4,
      humanFriendliness: 3,
      description:
        "I especially like going to the forest. I'm trained in finding eatable mushrooms, so your owner might want to skip dinner reservations.",
      briefDescription: 'Forest loving dog up for anything outdoors.',
      likes: ['sniffs', 'horses', 'outdoors', 'hugs', 'pets'],
      dislikes: ['hot', 'cars', 'bicycles', 'fireworks'],
      images: [
        'https://images.dog.ceo/breeds/germanshepherd/n02106662_13912.jpg',
        'https://images.dog.ceo/breeds/germanshepherd/n02106662_16149.jpg',
        'https://images.dog.ceo/breeds/germanshepherd/Hannah.jpg',
      ],
    },
    preferences: {
      size: ['Small', 'Medium', 'Large'],
      maxDistance: 11,
      gender: 'Both',
      energyLevel: [2, 3, 4],
    },
  },
  {
    userId: 'VctUVBo8YbX8hGYSVNM5vrLVtg13',
    name: 'Alex',
    email: 'alex@test.com',
    location: {
      city: 'London',
      county: 'Greater London',
      state: 'England',
      postcode: 'SE1 4HU',
      country: 'United Kingdom',
      countryCode: 'gb',
      lon: -0.094505,
      lat: 51.498161,
      stateCode: 'ENG',
      formatted:
        'Rutherford Lodge, 7 Brockham Street, London, SE1 4HU, United Kingdom',
      addressLine1: 'Rutherford Lodge',
      addressLine2: '7 Brockham Street, London, SE1 4HU, United Kingdom',
    },
    verified: false,
    notifications: true,
    darkMode: false,
    swipeYes: [],
    swipeNo: [],
    matches: [],
    ownerImage:
      'https://png.pngtree.com/png-vector/20191027/ourlarge/pngtree-user-icon-isolated-on-abstract-background-png-image_1875037.jpg',
    dog: {
      name: 'Emma',
      breed: 'Mix',
      age: 2,
      size: 'Medium',
      gender: 'Female',
      energyLevel: 3,
      dogFriendliness: 3,
      humanFriendliness: 4,
      description:
        'If you enjoy catching frisbees in the park, we are meant for eachother!',
      briefDescription: 'Frisbee lover!',
      likes: ['frisbee', 'horses', 'outdoors'],
      dislikes: ['cars', 'bicycles', 'fireworks'],
      images: [],
    },
    preferences: {
      size: ['Small', 'Medium'],
      maxDistance: 4,
      gender: 'Male',
      energyLevel: [2, 3, 4],
    },
  },
  {
    userId: 'jUIXoPI1tOMbFOXwph9YStubqZT2',
    name: 'James',
    email: 'james@test.com',
    location: {
      city: 'London',
      county: 'Greater London',
      state: 'England',
      postcode: 'SE17',
      country: 'United Kingdom',
      countryCode: 'gb',
      lon: -0.0922512,
      lat: 51.4977061,
      stateCode: 'ENG',
      formatted: 'Merrick Square, London, SE1 4JB, United Kingdom',
      addressLine1: 'Merrick Square',
      addressLine2: 'London, SE1 4JB, United Kingdom',
    },
    verified: true,
    notifications: true,
    darkMode: false,
    swipeYes: [],
    swipeNo: [],
    matches: [],
    ownerImage:
      'https://png.pngtree.com/png-vector/20191027/ourlarge/pngtree-user-icon-isolated-on-abstract-background-png-image_1875037.jpg',
    dog: {
      name: 'Berty',
      breed: 'Beagle',
      age: 3,
      size: 'Medium',
      gender: 'Male',
      energyLevel: 4,
      dogFriendliness: 4,
      humanFriendliness: 3,
      description:
        "I grew up with a lot of dogs and since I got adopted I've missed being in a pack. I'll make friends with just about any dog.",
      briefDescription: 'Seeking a group of like minded dogs.',
      likes: ['sniffs', 'horses', 'outdoors', 'hugs', 'pets'],
      dislikes: ['hot', 'cars', 'bicycles', 'fireworks'],
      images: [
        'https://images.dog.ceo/breeds/beagle/n02088364_639.jpg',
        'https://images.dog.ceo/breeds/beagle/n02088364_14613.jpg',
        'https://images.dog.ceo/breeds/beagle/n02088364_14690.jpg',
      ],
    },
    preferences: {
      size: ['Small', 'Medium', 'Large'],
      maxDistance: 0.75,
      gender: 'Both',
      energyLevel: [2, 3, 4],
    },
  },
  {
    userId: 'VzQh0Rz6oOcceVK9pqPSovIZRLm1',
    name: 'Raul',
    email: 'raul@test.com',
    location: {
      city: 'London',
      county: 'Greater London',
      state: 'England',
      postcode: 'SE1 4YG',
      country: 'United Kingdom',
      countryCode: 'gb',
      lon: -0.09139095000000394,
      lat: 51.49866165,
      stateCode: 'ENG',
      formatted: 'Shere House, Trinity Street, London, SE1 4YG, United Kingdom',
      addressLine1: 'Shere House',
      addressLine2: 'Trinity Street, London, SE1 4YG, United Kingdom',
    },
    verified: false,
    notifications: true,
    darkMode: false,
    swipeYes: [
      'VctUVBo8YbX8hGYSVNM5vrLVtg13',
      '4jg6OCap5PQ3FANMuoG1FONJBvF2',
      '8qw4gtm1VhWfcQDlfdNw7y9sQVm2',
      'jUIXoPI1tOMbFOXwph9YStubqZT2',
      'HsUxOdRgSbeq2oxCgAIox63m8oA3',
    ],
    swipeNo: [],
    matches: [
      {
        matchId: '8qw4gtm1VhWfcQDlfdNw7y9sQVm2',
        roomId: '8qw4gtm1VhVzQh0Rz6oO',
      },
      {
        matchId: '4jg6OCap5PQ3FANMuoG1FONJBvF2',
        roomId: 'VzQh0Rz6oO4jg6OCap5P',
      },
    ],
    ownerImage:
      'https://png.pngtree.com/png-vector/20191027/ourlarge/pngtree-user-icon-isolated-on-abstract-background-png-image_1875037.jpg',
    dog: {
      name: 'Maya',
      breed: 'Pyreness',
      age: 6,
      size: 'Medium',
      gender: 'Female',
      energyLevel: 4,
      dogFriendliness: 4,
      humanFriendliness: 3,
      description:
        'My name is Maya. I bark spanish but also english. Hit me up if you want to train your language skills!',
      briefDescription: 'Habla espanõl? I am seeking an amigo/amiga.',
      likes: ['sniffs', 'horses', 'outdoors', 'hugs', 'pets'],
      dislikes: ['hot', 'cars', 'bicycles', 'fireworks'],
      images: [
        'https://images.dog.ceo/breeds/pyrenees/n02111500_8319.jpg',
        'https://images.dog.ceo/breeds/pyrenees/n02111500_2617.jpg',
        'https://images.dog.ceo/breeds/pyrenees/n02111500_7218.jpg',
      ],
    },
    preferences: {
      size: ['Small', 'Medium', 'Large'],
      maxDistance: 0.75,
      gender: 'Both',
      energyLevel: [2, 3, 4],
    },
  },
];

export const matches = [
  {
    userId: '4jg6OCap5PQ3FANMuoG1FONJBvF2',
    matchIds: [],
  },
  {
    userId: 'HsUxOdRgSbeq2oxCgAIox63m8oA3',
    matchIds: [],
  },
  {
    userId: '8qw4gtm1VhWfcQDlfdNw7y9sQVm2',
    matchIds: [],
  },
  {
    userId: 'pBpXPtTC8tP3ARlhUn45IzHgKyp2',
    matchIds: [],
  },
  {
    userId: 'Z9R01fG87SYOQg1ASouLqPDskso2',
    matchIds: [],
  },
];

export const chats = [
  {
    roomId: '8qw4gtm1VhZ9R01fG87S',
    messages: [],
  },
  {
    roomId: '8qw4gtm1VhVzQh0Rz6oO',
    messages: [],
  },
  {
    roomId: 'VzQh0Rz6oO4jg6OCap5P',
    messages: [],
  },
  {
    roomId: 'Z9R01fG87S4jg6OCap5P',
    messages: [],
  },
];

export const events = [
  {
    createdBy: '4jg6OCap5PQ3FANMuoG1FONJBvF2',
    dateTime: new Date('2022-09-12T16:00'),
    location: {
      city: 'London',
      county: 'Greater London',
      state: 'England',
      postcode: 'HA3 9JS',
      country: 'United Kingdom',
      countryCode: 'gb',
      lon: -0.298049444,
      lat: 51.589386044,
      formatted: 'London, HA3 9JS, United Kingdom',
      addressLine1: 'London',
      addressLine2: 'HA3 9JS, United Kingdom',
    },
    briefDescription: 'German Shepard Club',
    description:
      'Want to join the London German Shepard Club? We are having an event in London where we will be talking about this fantastic breed. Bring your dog to socialize with the GS community.',
    images: [
      'https://cdn.londonandpartners.com/-/media/images/london/visit/things-to-do/place/greenwich-park-640x360.jpg?mw=640&hash=154B00A4E4191E1AC7AFA1AB4BE03733503CFD24',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcST5JYDEaDJ2scMsqzTxMtgtpJ1PjnoD7g4dTMJBUCm4kZCSDpAfmIu2ftJohZCdxrmjQU&usqp=CAU',
    ],
    attendees: [
      {
        userId: '4jg6OCap5PQ3FANMuoG1FONJBvF2',
        creator: true,
      },
      {
        userId: '8qw4gtm1VhWfcQDlfdNw7y9sQVm2',
        creator: false,
      },
    ],
  },
  {
    createdBy: '4jg6OCap5PQ3FANMuoG1FONJBvF2',
    dateTime: new Date('2022-08-29T15:30'),
    location: {
      city: 'London',
      county: 'Greater London',
      state: 'England',
      postcode: 'WC2A 3TP',
      country: 'United Kingdom',
      countryCode: 'gb',
      lon: -0.1150552,
      lat: 51.5166156,
      formatted: "Lincoln's Inn Fields, London, WC2A 3TP, United Kingdom",
      addressLine1: "Lincoln's Inn Fields",
      addressLine2: 'London, WC2A 3TP, United Kingdom',
    },
    briefDescription: 'Pup meet-up!',
    description:
      'If you got a pup. Meet up! Various activities are arranged: agility course, dog treat taste-off, talks on dog grooming and equipment. If you want to arrange an acitivity yourself go to www.watford-pup-meet-up.co.uk',
    images: [
      'https://www.cesarsway.com/wp-content/uploads/2019/09/AdobeStock_195276899.jpeg',
      'https://newtheory.com/wp-content/uploads/2015/02/puppies-hangin.jpg',
    ],
    attendees: [
      {
        userId: '4jg6OCap5PQ3FANMuoG1FONJBvF2',
        creator: true,
      },
    ],
  },
  {
    createdBy: '4jg6OCap5PQ3FANMuoG1FONJBvF2',
    dateTime: new Date('2022-09-02T09:00'),
    location: {
      city: 'London',
      county: 'Greater London',
      state: 'England',
      postcode: 'WC2',
      country: 'United Kingdom',
      countryCode: 'gb',
      lon: -0.1174991,
      lat: 51.5171721,
      formatted: 'Whetstone Park, London, WC2, United Kingdom',
      addressLine1: 'Whetstone Park',
      addressLine2: 'London, WC2, United Kingdom',
    },
    briefDescription: 'Big breeds and barbeque',
    description:
      'Do you like big dogs? Do you like barbeque? Why not join us in Whetstone park for a treat that both you and your dog will enjoy. Bring some meats or a salad, chairs will be arranged.',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/e/e7/Bluebells_%2834146232732%29.jpg',
    ],
    attendees: [
      {
        userId: '4jg6OCap5PQ3FANMuoG1FONJBvF2',
        creator: true,
      },
    ],
  },
  {
    createdBy: '4jg6OCap5PQ3FANMuoG1FONJBvF2',
    dateTime: new Date('2022-09-15T18:00'),
    location: {
      city: 'Westminster',
      county: 'Greater London',
      state: 'England',
      postcode: '',
      country: 'United Kingdom',
      countryCode: 'gb',
      lon: -0.14371934483944357,
      lat: 51.504458150000005,
      formatted:
        'The Green Park, Belgravia, Westminster, London, ENG, United Kingdom',
      addressLine1: 'The Green Park',
      addressLine2: 'Belgravia, Westminster, London, ENG, United Kingdom',
    },
    briefDescription: 'Agility for beginners',
    description:
      'Want to get started on agility for dogs? Sarah McGillan is now coming to Westminster to introduce you and your dog to agility. Sarah has won several national and international agility competitions, and has experience with a wide range of dog breeds. You will not look back!',
    images: [
      'https://www.forestryengland.uk/sites/default/files/styles/list_image_large_2x/public/media/1014578.jpg?itok=4UPCbXCB',
    ],
    attendees: [
      {
        userId: '4jg6OCap5PQ3FANMuoG1FONJBvF2',
        creator: true,
      },
      {
        userId: '8qw4gtm1VhWfcQDlfdNw7y9sQVm2',
        creator: false,
      },
    ],
  },
  {
    createdBy: '4jg6OCap5PQ3FANMuoG1FONJBvF2',
    dateTime: new Date('2022-09-12T10:00'),
    location: {
      city: 'London',
      county: 'Greater London',
      state: 'England',
      postcode: 'HA3 9JS',
      country: 'United Kingdom',
      countryCode: 'gb',
      lon: -0.18042659722479423,
      lat: 51.50664635,
      formatted:
        'Kensington Gardens, South Kensington, London, ENG, United Kingdom',
      addressLine1: 'Kensington Gardens',
      addressLine2: 'South Kensington, London, ENG, United Kingdom',
    },
    briefDescription: 'Frisbee shindig',
    description: "Let's throw some frisbees! All dogs are welcome.",
    images: [
      'https://www.owatroldirect.co.uk/wp-content/uploads/2018/11/river-3365287-e1542125037242.jpg',
      'https://www.drifters.co.uk/wp-content/uploads/2020/01/Golcar-Huddersfield-Narrow-Canal-1-1.jpg',
    ],
    attendees: [
      {
        userId: '4jg6OCap5PQ3FANMuoG1FONJBvF2',
        creator: true,
      },
    ],
  },
];
